# Generated by Django 2.2 on 2019-10-01 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('capacidad', models.IntegerField(blank=True, null=True, verbose_name='Capacidad')),
                ('horarios', models.TextField(verbose_name='Horarios')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='Autoridad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=120, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=200, null=True, verbose_name='Correo Electronico')),
                ('dni', models.IntegerField(verbose_name='Documento')),
                ('tel_fijo', models.CharField(max_length=50, null=True, verbose_name='Telefono Fijo')),
                ('celular', models.CharField(max_length=50, null=True, verbose_name='Celular')),
                ('domicilio', models.CharField(max_length=200, verbose_name='Domicilio')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('telefono_emergencia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefono de Emergencia')),
            ],
            options={
                'verbose_name': 'Autoridad',
                'verbose_name_plural': 'Autoridades',
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[('I', 'Ingreso'), ('E', 'Egreso')])),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('estado', models.IntegerField(choices=[('E', 'Excelente'), ('B', 'Bueno'), ('M', 'Malo'), ('R', 'En Reparacion')])),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
            },
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha del Recordatorio')),
            ],
        ),
        migrations.CreateModel(
            name='PagoAProveedores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha del Recordatorio')),
            ],
        ),
        migrations.CreateModel(
            name='PosibleCliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=150, verbose_name='Apellido')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electronico')),
                ('fecha_consulta', models.DateField(verbose_name='Fecha de Consulta')),
                ('actividad', models.TextField(verbose_name='Actividad Consultada')),
            ],
            options={
                'verbose_name': 'Posible Cliente',
                'verbose_name_plural': 'Posibles Clientes',
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=120, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=200, null=True, verbose_name='Correo Electronico')),
                ('dni', models.IntegerField(verbose_name='Documento')),
                ('tel_fijo', models.CharField(max_length=50, null=True, verbose_name='Telefono Fijo')),
                ('celular', models.CharField(max_length=50, null=True, verbose_name='Celular')),
                ('domicilio', models.CharField(max_length=200, verbose_name='Domicilio')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('profesion', models.CharField(max_length=70, verbose_name='Profesion')),
                ('matricula', models.CharField(max_length=50, verbose_name='Matricula')),
            ],
            options={
                'verbose_name': 'Profesional',
                'verbose_name_plural': 'Profesionales',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=120, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=200, null=True, verbose_name='Correo Electronico')),
                ('dni', models.IntegerField(verbose_name='Documento')),
                ('tel_fijo', models.CharField(max_length=50, null=True, verbose_name='Telefono Fijo')),
                ('celular', models.CharField(max_length=50, null=True, verbose_name='Celular')),
                ('domicilio', models.CharField(max_length=200, verbose_name='Domicilio')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('cuit', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cuit')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=120, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=200, null=True, verbose_name='Correo Electronico')),
                ('dni', models.IntegerField(verbose_name='Documento')),
                ('tel_fijo', models.CharField(max_length=50, null=True, verbose_name='Telefono Fijo')),
                ('celular', models.CharField(max_length=50, null=True, verbose_name='Celular')),
                ('domicilio', models.CharField(max_length=200, verbose_name='Domicilio')),
                ('ficha_medica', models.TextField(blank=True, null=True, verbose_name='Ficha Medica')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto de Perfil')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('telefono_emergencia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefono de Emergencia')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('saldo', models.BooleanField(default=True, verbose_name='Al dia / Debe')),
                ('observaciones_medicas', models.TextField(blank=True, null=True, verbose_name='Observaciones Medicas')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartGym.Actividad')),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=50, null=True, verbose_name='Direccion')),
                ('telefono', models.CharField(max_length=50, null=True, verbose_name='Telefono')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha del Turno')),
                ('es_fijo', models.BooleanField(default=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartGym.Actividad')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartGym.Socio')),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('duracion', models.CharField(max_length=50, verbose_name='Duracion de la Rutina')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo de Rutina')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartGym.Ejercicio')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartGym.Socio')),
            ],
            options={
                'verbose_name': 'Rutina',
                'verbose_name_plural': 'Rutinas',
            },
        ),
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('fecha', models.DateTimeField(verbose_name='Fecha del Recordatorio')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartGym.Socio')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartGym.Turno')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=120, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=200, null=True, verbose_name='Correo Electronico')),
                ('dni', models.IntegerField(verbose_name='Documento')),
                ('tel_fijo', models.CharField(max_length=50, null=True, verbose_name='Telefono Fijo')),
                ('celular', models.CharField(max_length=50, null=True, verbose_name='Celular')),
                ('domicilio', models.CharField(max_length=200, verbose_name='Domicilio')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto de Perfil')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('telefono_emergencia', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefono de Emergencia')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartGym.Sucursal')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha del Recordatorio')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('monto', models.IntegerField(verbose_name='Monto')),
                ('metodo', models.CharField(max_length=50, verbose_name='Metodo de Pago')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartGym.Socio')),
            ],
        ),
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('fecha', models.DateField(verbose_name='Fecha Inicio')),
                ('duracion_contrato', models.TextField(verbose_name='Duracion del Contrato')),
                ('horarios', models.TextField(verbose_name='Horarios')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartGym.Profesional')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartGym.Sucursal')),
            ],
            options={
                'verbose_name': 'Consultorio',
                'verbose_name_plural': 'Consultorios',
            },
        ),
        migrations.CreateModel(
            name='AsistenciaSocio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(verbose_name='Fecha de Ingreso')),
                ('hora_ingreso', models.DateTimeField(verbose_name='Hora de Ingreso')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartGym.Socio')),
            ],
            options={
                'verbose_name': 'Asistencia Socio',
                'verbose_name_plural': 'Asistencias Socios',
            },
        ),
        migrations.CreateModel(
            name='AsistenciaEmpleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(verbose_name='Fecha de Ingreso')),
                ('hora_ingreso', models.DateTimeField(verbose_name='Hora de Ingreso')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartGym.Empleado')),
            ],
            options={
                'verbose_name': 'Asistencia Empleado',
                'verbose_name_plural': 'Asistencias Empleados',
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartGym.Empleado'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmartGym.Sucursal'),
        ),
    ]
