# Generated by Django 2.2 on 2019-10-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartGym', '0002_auto_20191004_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoridad',
            name='dni',
            field=models.IntegerField(blank=True, null=True, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='dni',
            field=models.IntegerField(blank=True, null=True, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='dni',
            field=models.IntegerField(blank=True, null=True, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='dni',
            field=models.IntegerField(blank=True, null=True, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
