# Generated by Django 2.2 on 2019-10-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartGym', '0003_auto_20191008_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoridad',
            name='domicilio',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='domicilio',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='domicilio',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='domicilio',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Domicilio'),
        ),
    ]
