# Generated by Django 2.2 on 2019-10-09 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SmartGym', '0005_auto_20191008_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SmartGym.Empleado'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='horarios',
            field=models.TextField(blank=True, null=True, verbose_name='Horarios'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SmartGym.Sucursal'),
        ),
        migrations.AlterField(
            model_name='asistenciaempleado',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SmartGym.Empleado'),
        ),
        migrations.AlterField(
            model_name='asistenciaempleado',
            name='fecha_ingreso',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='asistenciaempleado',
            name='hora_ingreso',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora de Ingreso'),
        ),
        migrations.AlterField(
            model_name='asistenciasocio',
            name='fecha_ingreso',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='asistenciasocio',
            name='hora_ingreso',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora de Ingreso'),
        ),
        migrations.AlterField(
            model_name='asistenciasocio',
            name='socio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SmartGym.Socio'),
        ),
        migrations.AlterField(
            model_name='autoridad',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='consultorio',
            name='duracion_contrato',
            field=models.TextField(blank=True, null=True, verbose_name='Duracion del Contrato'),
        ),
        migrations.AlterField(
            model_name='consultorio',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='consultorio',
            name='horarios',
            field=models.TextField(blank=True, null=True, verbose_name='Horarios'),
        ),
        migrations.AlterField(
            model_name='consultorio',
            name='nombre',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='consultorio',
            name='profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SmartGym.Profesional'),
        ),
        migrations.AlterField(
            model_name='consultorio',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SmartGym.Sucursal'),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha del Recordatorio'),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='metodo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Metodo de Pago'),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='monto',
            field=models.IntegerField(blank=True, null=True, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='socio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SmartGym.Socio'),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='estado',
            field=models.IntegerField(blank=True, choices=[('E', 'Excelente'), ('B', 'Bueno'), ('M', 'Malo'), ('R', 'En Reparacion')], null=True),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='nombre',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='liquidacion',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha del Recordatorio'),
        ),
        migrations.AlterField(
            model_name='pagoaproveedores',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha del Recordatorio'),
        ),
        migrations.AlterField(
            model_name='posiblecliente',
            name='actividad',
            field=models.TextField(blank=True, null=True, verbose_name='Actividad Consultada'),
        ),
        migrations.AlterField(
            model_name='posiblecliente',
            name='apellido',
            field=models.CharField(max_length=150, null=True, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='posiblecliente',
            name='fecha_consulta',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Consulta'),
        ),
        migrations.AlterField(
            model_name='posiblecliente',
            name='nombre',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='matricula',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Matricula'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='profesion',
            field=models.CharField(blank=True, max_length=70, verbose_name='Profesion'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='domicilio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Domicilio'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='recordatorio',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha del Recordatorio'),
        ),
        migrations.AlterField(
            model_name='recordatorio',
            name='socio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SmartGym.Socio'),
        ),
        migrations.AlterField(
            model_name='recordatorio',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SmartGym.Turno'),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='duracion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Duracion de la Rutina'),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='ejercicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SmartGym.Ejercicio'),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='socio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SmartGym.Socio'),
        ),
        migrations.AlterField(
            model_name='rutina',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Rutina'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SmartGym.Actividad'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='es_fijo',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha del Turno'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='socio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SmartGym.Socio'),
        ),
    ]
