# Generated by Django 2.2 on 2019-10-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartGym', '0007_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='precio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Precio'),
        ),
    ]
