# Generated by Django 2.2 on 2019-10-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartGym', '0008_actividad_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoridad',
            name='genero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Genero'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='genero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Genero'),
        ),
        migrations.AddField(
            model_name='profesional',
            name='genero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Genero'),
        ),
        migrations.AddField(
            model_name='socio',
            name='genero',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Genero'),
        ),
    ]
