# Generated by Django 2.2 on 2019-10-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartGym', '0010_auto_20191021_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoridad',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='autoridad',
            name='tel_fijo',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='tel_fijo',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='tel_fijo',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='socio',
            name='tel_fijo',
        ),
        migrations.AddField(
            model_name='autoridad',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefono'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefono'),
        ),
        migrations.AddField(
            model_name='profesional',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefono'),
        ),
        migrations.AddField(
            model_name='profesional',
            name='telefono_emergencia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefono de Emergencia'),
        ),
        migrations.AddField(
            model_name='socio',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefono'),
        ),
    ]
