# Generated by Django 2.2 on 2019-10-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartGym', '0011_auto_20191022_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='empleado',
        ),
        migrations.AddField(
            model_name='actividad',
            name='empleados',
            field=models.ManyToManyField(blank=True, null=True, to='SmartGym.Empleado'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='actividades',
            field=models.ManyToManyField(blank=True, null=True, to='SmartGym.Actividad'),
        ),
    ]
