# Generated by Django 2.2 on 2019-10-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartGym', '0012_auto_20191023_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='ficha_medica',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Ficha Medica'),
        ),
    ]
