# Generated by Django 2.2 on 2019-10-29 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartGym', '0013_empleado_ficha_medica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='ficha_medica',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='foto',
        ),
    ]
