# Generated by Django 2.2 on 2019-11-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartGym', '0014_auto_20191029_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='empleados',
            field=models.ManyToManyField(blank=True, to='SmartGym.Empleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='actividades',
            field=models.ManyToManyField(blank=True, to='SmartGym.Actividad'),
        ),
    ]
