# Generated by Django 2.2 on 2019-11-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartGym', '0015_auto_20191103_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoridad',
            name='apellido',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='autoridad',
            name='nombre',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='apellido',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='apellido',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='nombre',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='apellido',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='nombre',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Nombres'),
        ),
    ]
