# Generated by Django 2.2 on 2019-12-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartGym', '0018_historicalsocio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sucursal',
            options={'verbose_name': 'Sucursal', 'verbose_name_plural': 'Sucursales'},
        ),
        migrations.AlterField(
            model_name='insumo',
            name='estado',
            field=models.CharField(blank=True, choices=[('Bueno', 'Bueno'), ('Malo', 'Malo'), ('A reparar', 'A reparar')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='HistoricalSocio',
        ),
    ]
