# Generated by Django 2.2 on 2019-12-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartGym', '0019_auto_20191209_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciaempleado',
            name='tipo',
            field=models.BooleanField(blank=True, choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], null=True),
        ),
        migrations.AlterField(
            model_name='autoridad',
            name='genero',
            field=models.CharField(blank=True, choices=[('Indefinido', 'Indefinido'), ('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=50, null=True, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='motivo',
            field=models.CharField(blank=True, choices=[('Pago a Proveedores', 'Pago a Proveedores'), ('Cobro Cuota', 'Cobro Cuota'), ('Otro', 'Otro')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='tipo',
            field=models.IntegerField(choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso')]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='genero',
            field=models.CharField(blank=True, choices=[('Indefinido', 'Indefinido'), ('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=50, null=True, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='genero',
            field=models.CharField(blank=True, choices=[('Indefinido', 'Indefinido'), ('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=50, null=True, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='genero',
            field=models.CharField(blank=True, choices=[('Indefinido', 'Indefinido'), ('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=50, null=True, verbose_name='Genero'),
        ),
    ]
