# Generated by Django 2.2 on 2019-12-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartGym', '0022_auto_20191209_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='tipo',
            field=models.CharField(choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso')], max_length=150),
        ),
    ]
