# Generated by Django 2.2 on 2019-12-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartGym', '0023_auto_20191210_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicio',
            name='musculo',
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='grupo_muscular',
            field=models.CharField(blank=True, choices=[('Piernas', 'Piernas'), ('Hombros', 'Hombros'), ('Biceps', 'Biceps'), ('Triceps', 'Triceps'), ('Pecho', 'Pecho'), ('Espalda', 'Espalda'), ('Core', 'Core'), ('Otro', 'Otro')], max_length=200, null=True, verbose_name='Grupo Muscular'),
        ),
    ]
