# Generated by Django 2.2 on 2019-12-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartGym', '0025_auto_20191210_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacion',
            name='monto_total',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=50, null=True, verbose_name='Total Liquidado'),
        ),
    ]
