# Generated by Django 2.2 on 2019-12-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartGym', '0026_auto_20191210_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutinaxejercicio',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=1000, null=True, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='rutinaxejercicio',
            name='series',
            field=models.IntegerField(blank=True, null=True, verbose_name='Series'),
        ),
    ]
