# Generated by Django 2.2 on 2019-12-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartGym', '0028_auto_20191210_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacion',
            name='monto_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Total Liquidado'),
        ),
    ]
