# Generated by Django 2.2 on 2019-12-10 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartGym', '0030_auto_20191210_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Monto'),
        ),
    ]
