# Generated by Django 2.2 on 2019-12-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartGym', '0033_auto_20191210_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='saldo',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Al dia / Deuda'),
        ),
    ]
