# Generated by Django 2.2 on 2019-12-10 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartGym', '0034_auto_20191210_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='encargado',
            field=models.CharField(max_length=50, null=True, verbose_name='Encargado'),
        ),
    ]
