# Generated by Django 2.2 on 2019-12-10 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SmartGym', '0035_sucursal_encargado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultorio',
            name='horarios',
        ),
        migrations.CreateModel(
            name='HorarioConsultorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Inicio')),
                ('hora_fin', models.DateTimeField(blank=True, null=True, verbose_name='Hora de Fin')),
                ('dia', models.DateField(blank=True, null=True, verbose_name='Dia de Atención')),
                ('consultorios', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SmartGym.Consultorio')),
                ('profesionales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SmartGym.Profesional')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
            },
        ),
        migrations.AddField(
            model_name='consultorio',
            name='horarios',
            field=models.ManyToManyField(blank=True, to='SmartGym.HorarioConsultorio'),
        ),
    ]
