# Generated by Django 2.2 on 2019-12-10 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartGym', '0037_auto_20191210_2348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horarioconsultorio',
            options={'verbose_name': 'Horario del Consultorio', 'verbose_name_plural': 'Horarios de los Consultorios'},
        ),
    ]
