# Generated by Django 2.2 on 2019-12-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartGym', '0038_auto_20191210_2355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caja',
            options={'verbose_name': 'Caja', 'verbose_name_plural': 'Registro de Cajas'},
        ),
        migrations.AlterModelOptions(
            name='cuota',
            options={'verbose_name': 'Cuota', 'verbose_name_plural': 'Control de Cuotas'},
        ),
        migrations.AlterModelOptions(
            name='horario',
            options={'verbose_name': 'Horario', 'verbose_name_plural': 'Horarios de las Actividades'},
        ),
        migrations.AlterModelOptions(
            name='liquidacion',
            options={'verbose_name': 'Liquidacion', 'verbose_name_plural': 'Liquidaciones de Empleados'},
        ),
        migrations.AlterModelOptions(
            name='posiblecliente',
            options={'verbose_name': 'Posible Cliente', 'verbose_name_plural': 'Registro de Posibles Clientes'},
        ),
        migrations.AddField(
            model_name='empleado',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Activo / Inactivo'),
        ),
        migrations.AddField(
            model_name='profesional',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Activo / Inactivo'),
        ),
        migrations.AddField(
            model_name='socio',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Activo / Inactivo'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='estado',
            field=models.CharField(blank=True, choices=[('Disponible', 'Disponible'), ('No disponible', 'No disponible'), ('En Reparacion', 'En Reparacion')], max_length=100, null=True),
        ),
    ]
