# Generated by Django 2.2 on 2019-12-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartGym', '0040_auto_20191211_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoridad',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes', verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes', verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes', verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='ficha_medica',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes', verbose_name='Ficha Medica'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes', verbose_name='Foto de Perfil'),
        ),
    ]
