# Generated by Django 2.2 on 2019-12-11 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartGym', '0042_auto_20191211_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='status',
            field=models.CharField(blank=True, choices=[('AC', 'Activo'), ('IN', 'Inactivo')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='estado',
            field=models.CharField(blank=True, choices=[('DIS', 'Disponible'), ('NO', 'No Disponible'), ('REP', 'A Reparar')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='status',
            field=models.CharField(blank=True, choices=[('AC', 'Activo'), ('IN', 'Inactivo')], max_length=150, null=True),
        ),
    ]
