# Generated by Django 2.2 on 2019-12-11 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SmartGym', '0043_auto_20191211_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='Sucursal de Alta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SmartGym.Sucursal'),
        ),
    ]
