# Generated by Django 2.2 on 2019-12-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartGym', '0044_socio_sucursal de alta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistenciaempleado',
            name='fecha_ingreso',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='asistenciaempleado',
            name='hora_ingreso',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Hora de Ingreso'),
        ),
        migrations.AlterField(
            model_name='asistenciasocio',
            name='fecha_ingreso',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='asistenciasocio',
            name='hora_ingreso',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Hora de Ingreso'),
        ),
    ]
