# Generated by Django 2.2 on 2019-12-12 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartGym', '0046_auto_20191212_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socio',
            old_name='Sucursal de Alta',
            new_name='sucursal',
        ),
    ]
