# Generated by Django 2.2 on 2019-12-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartGym', '0047_auto_20191212_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='cuenta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Cuenta'),
        ),
        migrations.AlterField(
            model_name='autoridad',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Foto de Perfil'),
        ),
    ]
