# Generated by Django 2.2 on 2019-12-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartGym', '0049_auto_20191216_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='hora_fin',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Hora de Fin'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='hora_inicio',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Hora de Inicio'),
        ),
        migrations.AlterField(
            model_name='horarioconsultorio',
            name='hora_fin',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Hora de Fin'),
        ),
        migrations.AlterField(
            model_name='horarioconsultorio',
            name='hora_inicio',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Hora de Inicio'),
        ),
    ]
